# Generated by Django 2.1.5 on 2019-01-23 20:07

from django.db import migrations, models
import main_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=main_content.models.get_image_path),
        ),
    ]
